apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      imagePullSecrets:
      - name: aliyun-acr-secret
      containers:
      - name: cicd-demo
        image: cri-c52fbf00w7ayauqn-cn-hangzhou.personal.cr.aliyuncs.com/ci-cd-xixi/ci-cd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
